
import 'package:flutter/material.dart';

const darkSecondaryColor = Color(0xFF0F0F0F);

const appName = 'PC Components Shop',
  appSince = 'Since 2022',
  appSlogan = 'Build your own PC with PC Configurator online and free! Choose any components you like and buy them!',
  home = 'Home',
  about = 'About',
  componentsList = 'PC Components List',
  totalCost = 'Total cost: ',
  clearSelection = 'Clear selection',
  submitOrder = 'Submit order',
  copyright = 'Copyright (C) 2022-2023 | Some rights reserved',
  aboutApp = 'About PC Components Shop',
  componentsSelection = 'PC Components Selection',
  searchByTitle = 'Search by title',
  empty = 'Empty',
  errorOccurred = 'An error has occurred',
  unknownError = 'Unknown error',
  noParametersProvidedError = 'No parameters have been provided to the page',
  submit = 'Submit',
  defaultCost = '0\$',
  firstName = 'First name',
  lastName = 'Last name',
  phoneNumber = 'Phone number',
  address = 'Address',
  loginPanel = 'Login panel',
  registrationPanel = 'Registration panel',
  login = 'Log in',
  login2 = 'Login',
  password = 'Password',
  register = 'Register',
  clear = 'Clear',
  databaseAdministration = 'Database administration',
  select = 'Select',
  insert = 'Insert',
  nullString = 'null',
  administrate = 'Administrate',
  viewDetails = 'View details',
  update = 'Update',
  delete = 'Delete',
  notSelected = 'Not selected',
  unauthorizedAsUser = 'Unauthorized, you must log in as user to proceed',
  wrongCredentials = 'Wrong credentials',
  nameExists = 'Name already exists',
  alreadyAuthorized = 'Authorization has been performed already',
  logout = 'Log out',
  notAllFieldsFilled = 'All text fields must be filled in',
  registrationSuccessful = 'Registration successfully performed',
  welcome = 'Welcome ',
  forbidden = 'Forbidden',
  unauthorizedAsAdmin = 'Unauthorized, you must log in as admin to proceed',
  stub = '',
  incorrectData = 'Incorrect data',
  operationSucceeded = 'Operation succeeded',
  operationFailed = 'Operation failed',
  nullable = '(nullable)',
  orders = 'Orders',
  unableToFetchOrders = 'Unable to fetch orders',
  orderHistory = 'Order history',
  ordersHistoryEmpty = 'Order history is empty',
  uploadFile = 'Upload file',
  deleteFile = 'Delete file',
  textEmpty = 'Text field is empty',
  fileName = 'File name',
  upload = 'Upload',
  enterFileName = 'Enter file name',
  viewFiles = 'View files',
  aboutText = '''We are Leading Company
Provide our customers with superior products and services at the most reasonable rates available. At the time of company formation in 2022, our core business was as a computer parts reseller. We initiated our company with the philosophy that “We refuse to compromise quality for profit” and have not since changed that guiding principle.

The quality of our custom built computers speak for themselves. They are reliable because we use brand name components which equals no headaches. PC Configurator sales and services focus on selling the best possible product at the best possible price. On a local level, PC Configurator’s exists to provide computer hardware and services. PC Configurator’s is very competitive on a national level in terms of price, quality and services. PC Configurator’s major market extends to all those with access to the internet and a web browser.''';

const appIcon = 'pc_icon.svg',
  svgExtension = '.svg',
  hardwareIcon = 'hwr_ico.svg',
  qualityIcon = 'qlt_ico.svg',
  jpgExtension = '.jpg';

const routeHome = '/',
  routeAbout = '/about',
  routeSelect = '/select',
  routeError = '/error',
  routeLogin = '/login',
  routeAdmin = '/admin';

const fetchAmount = 8;

const baseUrl = 'http://0.0.0.0:8080', imageUrl = '$baseUrl/res_back/';
